db:
  image: kartoza/postgis:9.4-2.1
  #volumes:
    #- ./pg/postgres_data:/var/lib/postgresql
  environment:
    - USERNAME=docker
    - PASS=docker

qgisserver:
  #build : .
  image: senoadiw/qgis-server
  hostname: qgis-server
  #volumes:
  #  - ./gis:/gis
  ports:
    - "8080:80"
  links:
    - db:db

#nginx:
#  image: nginx
#  hostname: nginx
#  volumes:
#    - ./nginx-conf:/etc/nginx/conf.d
#  ports:
#    - "0.0.0.0:8080:80"
#  links:
#    - qgisserver:qgisserver
